version: "3"
services:
  scrapper:
    build:
      dockerfile: Packtpub.Dockerfile
      context: .
    volumes:
      - ./store:/usr/app/store
    depends_on:
      - db
    environment:
      - bookid=${bookid}
      - user=${user}
      - pass=${pass}
      - MONGO_URL=mongodb://db:27017
      - TOKEN=${TOKEN}
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./store/mongo:/data/db
    restart: always