version: "3"
services:
  scrapper:
    build:
      dockerfile: Packtpub.Dockerfile
      context: .
    volumes:
      - ./store:/usr/app/store
    environment:
      - bookid=${bookid}
      - user=${user}
      - pass=${pass}
      - MONGO_URL=mongodb://db:27017
      - TOKEN=${TOKEN}
  db:
    image: mongo:latest
    volumes:
      - ./store/mongo:/data/db
    logging:
      driver: none
    depends_on:
      - scrapper
    restart: always